name: tests
 
on: [ push, pull_request ]
 
jobs:
  start-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "checks"
        uses: actions/checkout@v4
 
      - name: "tests"
        run: ./gradlew test

